project_id = "qzjfbqirbxsqdwcbpsst"

[functions.send-application-notification]
verify_jwt = false

[functions.send-digest-emails]
verify_jwt = false

[functions.send-status-update]
verify_jwt = false
